spring:
  application:
    name: EmailService-dev
  datasource:
    url: jdbc:mysql://localhost:3306/email_service
    username: dbUser
    password: dbUser
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: default

  jpa:
    hibernate:
      ddl-auto: update                                    # Possible values: none, update, validate, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
      group-id: email-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


server:
  port: 2012

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
