spring:
  application:
    name: EmailService-dev
  datasource:
    url: jdbc:mysql://localhost:3306/email_service
    username: dbUser
    password: dbUser
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: default

  jpa:
    hibernate:
      ddl-auto: update                                    # Possible values: none, update, validate, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: ${KAFKA_SERVER:192.168.1.1:9092}

    consumer:
      # Config for consuming normal strings
      normal:
        group-id: string-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      # Config for consuming JSON objects
      json:
        group-id: json-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.value.default.type: in.rajlabs.EmailService.dto.EmailerInfo

    producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


server:
  port: 2012

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
